- topic_name: /tf
  msg_type: tf2_msgs/msg/TFMessage
- topic_name: /follower/localisation/filtered_odom
  msg_type: nav_msgs/msg/Odometry
- topic_name: /leader/localisation/filtered_odom
  msg_type: nav_msgs/msg/Odometry
- topic_name: /follower/imu/data
  msg_type: sensor_msgs/msg/Imu
- topic_name: /leader/imu/data
  msg_type: sensor_msgs/msg/Imu
- topic_name: /follower/alpo_driver/joint_states
  msg_type: sensor_msgs/msg/JointState
- topic_name: /leader/alpo_driver/joint_states
  msg_type: sensor_msgs/msg/JointState
- topic_name: /follower/alpo_driver/ackermann_controller/desired_state
  msg_type: sensor_msgs/msg/JointState
- topic_name: /leader/alpo_driver/ackermann_controller/desired_state
  msg_type: sensor_msgs/msg/JointState
- topic_name: /follower/alpo_driver/ackermann_controller/odom
  msg_type: nav_msgs/msg/Odometry
- topic_name: /leader/alpo_driver/ackermann_controller/odom
  msg_type: nav_msgs/msg/Odometry
- topic_name: /follower/alpo_driver/ackermann_controller/drive_state
  msg_type: ackermann_msgs/msg/AckermannDriveStamped
- topic_name: /leader/alpo_driver/ackermann_controller/drive_state
  msg_type: ackermann_msgs/msg/AckermannDriveStamped
- topic_name: /leader/furrow_following/detection/odom
  msg_type: geometry_msgs/msg/Pose
- topic_name: /leader/lidar/scan
  msg_type: sensor_msgs/msg/LaserScan
- topic_name: /follower/lidar2/points
  msg_type: sensor_msgs/msg/PointCloud2
- topic_name: /follower/gps/nmea_sentence
  msg_type: nmea_msgs/msg/Sentence
- topic_name: /leader/gps/nmea_sentence
  msg_type: nmea_msgs/msg/Sentence
- topic_name: /follower/gps/fix
  msg_type: sensor_msgs/msg/NavSatFix
- topic_name: /leader/gps/fix
  msg_type: sensor_msgs/msg/NavSatFix
- topic_name: /leader/joy
  msg_type: sensor_msgs/msg/Joy
- topic_name: /follower/joy
  msg_type: sensor_msgs/msg/Joy
